services:
  backend:
    build: .
    container_name: ecom-backend
    ports:
      - "2004:2004"
    env_file: .env
    
    volumes:
      - ./uploads:/app/uploads
    
    depends_on:
      - postgres
    
    networks:
      - ecom-network
    
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: ecom-postgres
    env_file: .env
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/01-init.sh
    
    networks:
      - ecom-network
    
    restart: unless-stopped

volumes:
  postgres_data:
    name: ecom_postgres_data

networks:
  ecom-network:
    driver: bridge
